export { default as noMatch } from "./404"
export { default as Buy } from "./buy"
export { default as Home } from "./home"
export { default as Cart } from "./cart"
export { default as Login } from "./login"
export { default as Orders } from "./orders"
export { default as Register } from "./register"
export { default as Account } from "./account"